#pragma once
#define IN_MAX_LEN_TEXT 1024*1024
#define IN_CODE_ENDL '|'
#define IN_CODE_TABLE {\
	INTAB::F, INTAB::F, INTAB::F, INTAB::F, INTAB::F, INTAB::F, INTAB::F, INTAB::F, INTAB::F, INTAB::F, '|', INTAB::F, INTAB::F, INTAB::F, INTAB::F, INTAB::F,\
	INTAB::F, INTAB::F, INTAB::F, INTAB::F, INTAB::F, INTAB::F, INTAB::F, INTAB::F, INTAB::F, INTAB::F, INTAB::F, INTAB::F, INTAB::F, INTAB::F, INTAB::F, INTAB::F,\
	INTAB::F, INTAB::F, INTAB::F, INTAB::F, INTAB::F, INTAB::F, INTAB::F, INTAB::F, INTAB::F, INTAB::F, INTAB::F, INTAB::F, INTAB::F, INTAB::F, INTAB::F, INTAB::F,\
	INTAB::T/*0*/, INTAB::F, INTAB::T/*2*/, INTAB::F, INTAB::F, INTAB::F, INTAB::T/*6*/, INTAB::F, INTAB::F, INTAB::F, INTAB::F, INTAB::F, INTAB::F, INTAB::F, INTAB::F, INTAB::F,\
	INTAB::F, INTAB::T/*A*/, INTAB::T/*B*/, INTAB::F, INTAB::F, INTAB::T/*E*/, INTAB::F, INTAB::F, INTAB::F, INTAB::T/*I*/, INTAB::F, INTAB::F, INTAB::F, INTAB::F, INTAB::T/*N*/, INTAB::F,\
	INTAB::F, INTAB::F, INTAB::T/*R*/, INTAB::T/*S*/, INTAB::F, INTAB::T/*U*/, INTAB::F, INTAB::F, INTAB::I/*ign X*/, INTAB::T/*Y*/, '!'/*Z*/, INTAB::F, INTAB::F, INTAB::F, INTAB::F, INTAB::F,\
	INTAB::F, INTAB::T/*a*/, INTAB::T/*b*/, INTAB::F, INTAB::F, INTAB::T/*e*/, INTAB::F, INTAB::F, INTAB::F, INTAB::T/*i*/, INTAB::F, INTAB::F, INTAB::F, INTAB::F, INTAB::T/*n*/, INTAB::F,\
	INTAB::F, INTAB::F, INTAB::T/*r*/, INTAB::T/*s*/, INTAB::F, INTAB::T/*u*/, INTAB::F, INTAB::F, INTAB::I/*ign x*/, INTAB::T/*y*/, INTAB::F, INTAB::F, INTAB::F, INTAB::F, INTAB::F, INTAB::F,\
																																								   \
	INTAB::F, INTAB::F, INTAB::F, INTAB::F, INTAB::F, INTAB::F, INTAB::F, INTAB::F, INTAB::F, INTAB::F, INTAB::F, INTAB::F, INTAB::F, INTAB::F, INTAB::F, INTAB::F,\
	INTAB::F, INTAB::F, INTAB::F, INTAB::F, INTAB::F, INTAB::F, INTAB::F, INTAB::F, INTAB::F, INTAB::F, INTAB::F, INTAB::F, INTAB::F, INTAB::F, INTAB::F, INTAB::F,\
	INTAB::F, INTAB::F, INTAB::F, INTAB::F, INTAB::F, INTAB::F, INTAB::F, INTAB::F, INTAB::F, INTAB::F, INTAB::F, INTAB::F, INTAB::F, INTAB::F, INTAB::F, INTAB::F,\
	INTAB::F, INTAB::F, INTAB::F, INTAB::F, INTAB::F, INTAB::F, INTAB::F, INTAB::F, INTAB::F, INTAB::F, INTAB::F, INTAB::F, INTAB::F, INTAB::F, INTAB::F, INTAB::F,\
	INTAB::T/*A*/, INTAB::T/*Á*/, INTAB::F, INTAB::F, INTAB::F, INTAB::T/*Å*/, INTAB::F, INTAB::F, INTAB::T/*È*/, INTAB::T/*É*/, INTAB::F, INTAB::F,INTAB::F, INTAB::T/*H*/, INTAB::F, INTAB::F,\
	INTAB::T/*P*/, INTAB::T/*C*/, INTAB::F, INTAB::T/*Ó*/, INTAB::F, INTAB::F, INTAB::F, INTAB::F, INTAB::F, INTAB::F, INTAB::F, INTAB::F, INTAB::F, INTAB::F, INTAB::F, INTAB::F,\
	INTAB::T/*a*/, INTAB::T/*á*/, INTAB::F, INTAB::F, INTAB::F, INTAB::T/*e*/, INTAB::F, INTAB::F, INTAB::T/*è*/, INTAB::T/*é*/, INTAB::F, INTAB::F, INTAB::F, INTAB::T/*í*/, INTAB::F, INTAB::F,\
	INTAB::T/*p*/, INTAB::T/*c*/, INTAB::F, INTAB::T/*ó*/, INTAB::F, INTAB::F, INTAB::F, INTAB::F, INTAB::F, INTAB::F, INTAB::F, INTAB::F, INTAB::F, INTAB::F, INTAB::F, INTAB::F,\
}

namespace In
{
	struct INTAB
	{
		enum codes {T = 1024, F = 2048, I = 4096};
		int size;
		int lines;
		int ignor;
		unsigned char* text;
		int code[256];
	};
	INTAB getin(wchar_t infile[], wchar_t outfile[]);
}